"""empty message

Revision ID: 16ff3222953f
Revises: 969f8c88a73c
Create Date: 2021-08-22 23:09:40.037144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16ff3222953f'
down_revision = '969f8c88a73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('label_id')
    )
    op.create_table('prediction',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request.request_id'], ),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('label')
    # ### end Alembic commands ###
