"""empty message

Revision ID: 969f8c88a73c
Revises: 
Create Date: 2021-08-22 23:07:40.058753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969f8c88a73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('feature_one', sa.Float(), nullable=True),
    sa.Column('feature_two', sa.Float(), nullable=True),
    sa.Column('feature_three', sa.Float(), nullable=True),
    sa.Column('feature_four', sa.Float(), nullable=True),
    sa.Column('feature_five', sa.Integer(), nullable=True),
    sa.Column('feature_six', sa.Integer(), nullable=True),
    sa.Column('feature_seven', sa.Integer(), nullable=True),
    sa.Column('feature_eight', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    # ### end Alembic commands ###
